export const AUTHORS = [
  {
    id: 'ines-calder',
    name: 'Inés Calder',
    initials: 'IC',
    bio: 'Inés Calder grew up between Buenos Aires and Bristol, and her writing lives in the space between those two cities — humid, searching, and alive to the sound of water. Her debut novel won the Hartley Prize for New Fiction. She now lives in Edinburgh with too many notebooks.',
    followers: 1240,
    books: ['the-long-marsh', 'salt-cartography'],
    social: { twitter: '#', instagram: '#' },
  },
  {
    id: 'marcus-obi',
    name: 'Marcus Obi',
    initials: 'MO',
    bio: 'Marcus Obi is a poet and essayist from Lagos by way of London. His work has appeared in Granta, The Dark Mountain Project, and several anthologies of contemporary African writing.',
    followers: 892,
    books: ['iron-latitudes', 'the-delta-hymns'],
  },
  {
    id: 'claire-fenn',
    name: 'Claire Fenn',
    initials: 'CF',
    bio: 'Claire Fenn spent fifteen years as a marine biologist before she started writing. Her memoir tracks both disciplines — the science of oceanic systems and the stranger science of grief.',
    followers: 674,
    books: ['depth-sounding'],
  },
  {
    id: 'samir-voss',
    name: 'Samir Voss',
    initials: 'SV',
    bio: 'Samir Voss writes speculative fiction rooted in Near-East mythology. He is based in Beirut and his first collection was shortlisted for the Shirley Jackson Award.',
    followers: 510,
    books: ['the-cartographer-of-lost-cities', 'dusk-protocols'],
  },
  {
    id: 'yuki-tanada',
    name: 'Yuki Tanada',
    initials: 'YT',
    bio: 'Yuki Tanada is a memoirist and essayist living in Kyoto. Her work explores displacement, inheritance, and the persistence of language across generations.',
    followers: 438,
    books: ['mother-tongue-mother-land', 'the-quiet-room'],
  },
];

export const BOOKS = [
  {
    id: 'the-long-marsh',
    title: 'The Long Marsh',
    author: 'Inés Calder',
    authorId: 'ines-calder',
    genre: 'fiction',
    coverColor: 'cover-clay',
    blurb: 'A novel about two women mapping the wetlands at the edge of a drowning town — and the archive they accidentally become. Longlisted for the Booker Prize.',
    sample: [
      'The marsh had its own grammar. You learned it the way you learned the grammar of an estuary — not from a book, but by wading in until the bottom became unreliable, until each step was also a question.',
      'Marta kept the field notebooks in order of their unreliability. The ones she trusted least she filed first. "Certainty is a form of forgetting," she told Luz on their second day out. Luz had not yet decided whether this was wisdom or a way of avoiding being wrong.',
      'By October the reed beds had grown so dense that the light arrived late and left early, like a visitor who was never quite comfortable. They worked in that compressed day, measuring and noting, and when they spoke it was in the shorthand of people who have learned to share a silence.',
    ],
    buyLink: '#',
    price: 9.99,
    publishedAt: '2024-03',
  },
  {
    id: 'salt-cartography',
    title: 'Salt Cartography',
    author: 'Inés Calder',
    authorId: 'ines-calder',
    genre: 'fiction',
    coverColor: 'cover-ochre',
    blurb: 'A collection of linked stories set along the Atlantic coast, where the past keeps washing up.',
    buyLink: '#',
    price: 7.99,
    publishedAt: '2023-09',
  },
  {
    id: 'iron-latitudes',
    title: 'Iron Latitudes',
    author: 'Marcus Obi',
    authorId: 'marcus-obi',
    genre: 'poetry',
    coverColor: 'cover-ink',
    blurb: 'A debut collection navigating the space between Lagos and London, between inheritance and invention. Raw, precise, and formally daring.',
    buyLink: '#',
    price: 6.99,
    publishedAt: '2024-01',
  },
  {
    id: 'the-delta-hymns',
    title: 'The Delta Hymns',
    author: 'Marcus Obi',
    authorId: 'marcus-obi',
    genre: 'poetry',
    coverColor: 'cover-clay-dark',
    blurb: "Odes to water, oil, migration, and music — Obi's second collection arrives fully formed.",
    buyLink: '#',
    price: 6.99,
    publishedAt: '2024-11',
  },
  {
    id: 'depth-sounding',
    title: 'Depth Sounding',
    author: 'Claire Fenn',
    authorId: 'claire-fenn',
    genre: 'memoir',
    coverColor: 'cover-clay',
    blurb: "A marine biologist reckons with her mother's death at the same time as a catastrophic coral bleaching event. Grief and science turn out to ask the same questions.",
    buyLink: '#',
    price: 8.99,
    publishedAt: '2023-11',
  },
  {
    id: 'the-cartographer-of-lost-cities',
    title: 'The Cartographer of Lost Cities',
    author: 'Samir Voss',
    authorId: 'samir-voss',
    genre: 'fiction',
    coverColor: 'cover-ochre',
    blurb: 'A speculative novel in which a woman discovers she can read the ghost-maps of cities that were destroyed. Steeped in Near-East mythology and genuinely unsettling.',
    buyLink: '#',
    price: 9.99,
    publishedAt: '2024-06',
  },
  {
    id: 'dusk-protocols',
    title: 'Dusk Protocols',
    author: 'Samir Voss',
    authorId: 'samir-voss',
    genre: 'fiction',
    coverColor: 'cover-clay-dark',
    blurb: 'Six interlinked stories set at the edge of the survivable world.',
    buyLink: '#',
    price: 7.99,
    publishedAt: '2023-05',
  },
  {
    id: 'mother-tongue-mother-land',
    title: 'Mother Tongue, Mother Land',
    author: 'Yuki Tanada',
    authorId: 'yuki-tanada',
    genre: 'memoir',
    coverColor: 'cover-sand',
    blurb: 'What happens to a language when the people who speak it move away? Tanada traces three generations of displacement through the Japanese her grandmother refused to teach her.',
    buyLink: '#',
    price: 8.99,
    publishedAt: '2024-04',
  },
  {
    id: 'the-quiet-room',
    title: 'The Quiet Room',
    author: 'Yuki Tanada',
    authorId: 'yuki-tanada',
    genre: 'nonfiction',
    coverColor: 'cover-ink',
    blurb: 'A meditation on silence — in architecture, in grief, in the space between languages.',
    buyLink: '#',
    price: 7.99,
    publishedAt: '2023-07',
  },
  {
    id: 'iron-latitudes-ii',
    title: 'Iron Latitudes II',
    author: 'Marcus Obi',
    authorId: 'marcus-obi',
    genre: 'poetry',
    coverColor: 'cover-clay',
    blurb: "The follow-up to Iron Latitudes continues Obi's formal experiments with the sonnet and the praise-song.",
    buyLink: '#',
    price: 6.99,
    publishedAt: '2025-01',
  },
  {
    id: 'the-high-water-mark',
    title: 'The High Water Mark',
    author: 'Claire Fenn',
    authorId: 'claire-fenn',
    genre: 'nonfiction',
    coverColor: 'cover-ochre',
    blurb: 'Essays on climate, measurement, and what we choose to record when time is running out.',
    buyLink: '#',
    price: 8.49,
    publishedAt: '2024-09',
  },
  {
    id: 'borderlands-notebook',
    title: 'Borderlands Notebook',
    author: 'Inés Calder',
    authorId: 'ines-calder',
    genre: 'nonfiction',
    coverColor: 'cover-clay-dark',
    blurb: 'A hybrid work of essays and field notes written during a year of travel along contested borders.',
    buyLink: '#',
    price: 7.49,
    publishedAt: '2025-02',
  },
];

export const GENRES = ['fiction', 'memoir', 'poetry', 'nonfiction'];

export function getBook(id) { return BOOKS.find(b => b.id === id); }
export function getAuthor(id) { return AUTHORS.find(a => a.id === id); }
export function getAuthorBooks(authorId) { return BOOKS.filter(b => b.authorId === authorId); }
