/**
 * Enrichment script — fetches cover images and buy links
 * from Open Library (free, no API key, no quota).
 * Prices are set to null (Open Library doesn't carry retail prices).
 *
 * Outputs: supabase/migrations/0011_enrich_catalogue.sql
 * Run:     node scripts/enrich-books.mjs
 * Then:    supabase db push
 */

import { createClient } from '@supabase/supabase-js';
import { writeFileSync, readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

// Load .env manually (no dotenv dep needed)
const __dir = dirname(fileURLToPath(import.meta.url));
const envPath = resolve(__dir, '../.env');
const env = Object.fromEntries(
  readFileSync(envPath, 'utf8')
    .split('\n')
    .filter(l => l.includes('='))
    .map(l => l.split('=').map(s => s.trim()))
);

const SUPABASE_URL  = env['VITE_SUPABASE_URL'];
const SUPABASE_KEY  = env['VITE_SUPABASE_ANON_KEY'];

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY in .env');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

const sleep = ms => new Promise(r => setTimeout(r, ms));

function esc(str) {
  if (!str) return 'NULL';
  return `'${str.replace(/'/g, "''")}'`;
}

function bookshopUrl(title, author) {
  const q = encodeURIComponent(`${title} ${author}`);
  return `https://bookshop.org/search?keywords=${q}`;
}

function openLibrarySearchUrl(title, author) {
  const t = encodeURIComponent(title);
  const a = encodeURIComponent(author);
  return `https://openlibrary.org/search?title=${t}&author=${a}`;
}

async function fetchOpenLibrary(title, author) {
  // Open Library search
  const t = encodeURIComponent(title);
  const a = encodeURIComponent(author.split(' ').slice(-1)[0]); // last name only — more reliable
  const url = `https://openlibrary.org/search.json?title=${t}&author=${a}&limit=5&fields=key,title,author_name,cover_i,isbn,first_publish_year`;

  let data;
  try {
    const res = await fetch(url, {
      headers: { 'User-Agent': 'IndieConverters/1.0 (educational project; tongeche@gmail.com)' }
    });
    if (!res.ok) {
      console.error(`  HTTP ${res.status}`);
      return null;
    }
    data = await res.json();
  } catch (e) {
    console.error(`  fetch error: ${e.message}`);
    return null;
  }

  const docs = data.docs || [];
  if (!docs.length) return null;

  // Pick best match — prefer where title matches closely
  const tLower = title.toLowerCase();
  const best = docs.find(d => d.title?.toLowerCase() === tLower)
    || docs.find(d => d.title?.toLowerCase().startsWith(tLower.slice(0, 6)))
    || docs[0];

  const coverId = best.cover_i;
  const thumbnail = coverId
    ? `https://covers.openlibrary.org/b/id/${coverId}-M.jpg`
    : null;

  const olUrl = `https://openlibrary.org${best.key}`;

  return { thumbnail, olUrl };
}

async function main() {
  // ── 1. Fetch all books + primary author ──────────────────────
  const { data: books, error } = await supabase
    .from('books')
    .select(`
      id, slug, title,
      books_authors ( position, authors ( display_name ) )
    `)
    .eq('is_published', true)
    .order('created_at');

  if (error) { console.error('Supabase error:', error.message); process.exit(1); }
  console.log(`\nEnriching ${books.length} books via Open Library…\n`);

  // ── 2. Call API for each book ─────────────────────────────────
  const results = [];

  for (const book of books) {
    const authorEntry = [...(book.books_authors || [])]
      .sort((a, b) => (a.position ?? 1) - (b.position ?? 1))[0];
    const author = authorEntry?.authors?.display_name || '';

    process.stdout.write(`  ${book.title.padEnd(50).slice(0, 50)} `);

    const enriched = await fetchOpenLibrary(book.title, author);

    const cover  = enriched?.thumbnail || null;
    const olUrl  = enriched?.olUrl     || null;
    const bsUrl  = bookshopUrl(book.title, author);
    const olSearchUrl = openLibrarySearchUrl(book.title, author);

    console.log(cover ? `✓ cover` : `✗ no cover`);

    results.push({ ...book, author, cover, olUrl, bsUrl, olSearchUrl });
    await sleep(200); // be polite to Open Library
  }

  // ── 3. Generate migration SQL ─────────────────────────────────
  const lines = [
    '-- Auto-generated by scripts/enrich-books.mjs',
    '-- Adds cover_url (Open Library) and buy links (Open Library + Bookshop.org).',
    '',
  ];

  // cover_url updates
  let updateCount = 0;
  for (const r of results) {
    if (!r.cover) continue;
    lines.push(`UPDATE public.books SET cover_url = ${esc(r.cover)} WHERE slug = ${esc(r.slug)};`);
    updateCount++;
  }

  lines.push('');
  lines.push('-- Ensure open-library retailer exists');
  lines.push(`INSERT INTO public.retailers (slug, label) VALUES ('open-library', 'Open Library') ON CONFLICT (slug) DO NOTHING;`);

  lines.push('');
  lines.push('-- Buy links (Open Library + Bookshop.org)');

  // Use a single DO block for all retailer link inserts
  lines.push(`DO $$`);
  lines.push(`DECLARE`);
  lines.push(`  ol_id uuid; bs_id uuid; book_id uuid;`);
  lines.push(`BEGIN`);
  lines.push(`  SELECT id INTO ol_id FROM public.retailers WHERE slug = 'open-library';`);
  lines.push(`  SELECT id INTO bs_id FROM public.retailers WHERE slug = 'bookshop';`);
  lines.push('');

  for (const r of results) {
    const buyUrl = r.olUrl || r.olSearchUrl;
    lines.push(`  SELECT id INTO book_id FROM public.books WHERE slug = ${esc(r.slug)};`);
    lines.push(`  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)`);
    lines.push(`    VALUES (book_id, ol_id, ${esc(buyUrl)})`);
    lines.push(`    ON CONFLICT DO NOTHING;`);
    lines.push(`  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)`);
    lines.push(`    VALUES (book_id, bs_id, ${esc(r.bsUrl)})`);
    lines.push(`    ON CONFLICT DO NOTHING;`);
    lines.push('');
  }

  lines.push(`END $$;`);

  // ── 4. Write migration file ───────────────────────────────────
  const outPath = resolve(__dir, '../supabase/migrations/0011_enrich_catalogue.sql');
  writeFileSync(outPath, lines.join('\n'), 'utf8');

  const covered = results.filter(r => r.cover).length;

  console.log(`\n─────────────────────────────────`);
  console.log(`Covers found   : ${covered} / ${results.length}`);
  console.log(`Buy links      : ${results.length * 2} (Open Library + Bookshop.org for every book)`);
  console.log(`\nMigration written → supabase/migrations/0011_enrich_catalogue.sql`);
  console.log(`Next: supabase db push`);
}

main().catch(e => { console.error(e); process.exit(1); });
