-- ============================================================
-- 0009_seed_catalogue.sql
-- Seed the Indie Converters catalogue (55 books from Google Sheet)
-- ============================================================

-- ── 1. IMPRINT ──────────────────────────────────────────────
INSERT INTO public.imprints (slug, name, mission) VALUES
  ('indieconverters-originals', 'IndieConverters Originals', 'Indie craft, major reach.')
ON CONFLICT (slug) DO NOTHING;

-- ── 2. GENRES ───────────────────────────────────────────────
INSERT INTO public.genres (slug, label) VALUES
  ('fiction',                 'Fiction'),
  ('nonfiction',              'Nonfiction'),
  ('self-help',               'Self-Help'),
  ('gothic-fiction',          'Gothic Fiction'),
  ('literary-horror',         'Literary Horror'),
  ('psychological-thriller',  'Psychological Thriller'),
  ('dark-academia',           'Dark Academia'),
  ('speculative-fiction',     'Speculative Fiction'),
  ('magical-realism',         'Magical Realism'),
  ('african-literary-fiction','African Literary Fiction'),
  ('psychology',              'Psychology'),
  ('trauma',                  'Trauma & Healing'),
  ('habits',                  'Habits & Behaviour'),
  ('relationships',           'Relationships'),
  ('philosophy',              'Philosophy')
ON CONFLICT (slug) DO NOTHING;

-- ── 3. RETAILERS ────────────────────────────────────────────
INSERT INTO public.retailers (slug, label) VALUES
  ('goodreads', 'Goodreads'),
  ('amazon',    'Amazon'),
  ('bookshop',  'Bookshop.org')
ON CONFLICT (slug) DO NOTHING;

-- ── 4. AUTHORS ──────────────────────────────────────────────
INSERT INTO public.authors (slug, display_name, short_bio) VALUES
  ('melissa-albert',            'Melissa Albert',                  'Author of atmospheric, fairy-tale-tinged literary fiction.'),
  ('mona-awad',                 'Mona Awad',                       'Known for dark, satirical literary fiction exploring obsession and belonging.'),
  ('silvia-moreno-garcia',      'Silvia Moreno-Garcia',            'Award-winning author blending Gothic horror with Latin American settings.'),
  ('t-kingfisher',              'T. Kingfisher',                   'Horror and fantasy author praised for her atmospheric, unsettling fiction.'),
  ('mariana-enriquez',          'Mariana Enriquez',                'Argentine author of literary horror rooted in political and personal darkness.'),
  ('rachel-yoder',              'Rachel Yoder',                    'Author of feminist magical realism exploring motherhood and rage.'),
  ('bora-chung',                'Bora Chung',                      'South Korean speculative fiction writer translated by Anton Hur.'),
  ('akwaeke-emezi',             'Akwaeke Emezi',                   'Multidisciplinary artist and author of emotionally charged literary fiction.'),
  ('jennifer-nansubuga-makumbi','Jennifer Nansubuga Makumbi',      'Ugandan novelist known for sweeping, intergenerational African storytelling.'),
  ('oyinkan-braithwaite',       'Oyinkan Braithwaite',             'Nigerian author whose dark comedies subvert crime fiction conventions.'),
  ('cassandra-l-thompson',      'Cassandra L. Thompson',           'Small press author of dark speculative fiction.'),
  ('lv-russell',                'L.V. Russell',                    'Small press Gothic fiction author with a talent for atmosphere and dread.'),
  ('jonathan-haidt',            'Jonathan Haidt',                  'Social psychologist and professor at NYU Stern, author of several landmark works on morality and anxiety.'),
  ('anna-lembke',               'Anna Lembke',                     'Chief of Addiction Medicine at Stanford and author on dopamine and modern craving.'),
  ('johann-hari',               'Johann Hari',                     'Journalist and author investigating attention, depression, and modern life.'),
  ('gabor-mate',                'Gabor Maté',                      'Physician and author exploring the connection between trauma, culture, and health.'),
  ('nedra-glover-tawwab',       'Nedra Glover Tawwab',             'Licensed therapist and bestselling author on boundaries and mental wellbeing.'),
  ('oliver-burkeman',           'Oliver Burkeman',                 'Author and journalist writing on time, mortality, and the limits of productivity.'),
  ('brianna-wiest',             'Brianna Wiest',                   'Author and essayist focused on self-sabotage and emotional healing.'),
  ('james-clear',               'James Clear',                     'Author and speaker on habits, decision-making, and continuous improvement.'),
  ('lori-gottlieb',             'Lori Gottlieb',                   'Psychotherapist, author, and Atlantic contributor known for candid writing on therapy.'),
  ('lindsay-c-gibson',          'Lindsay C. Gibson',               'Clinical psychologist specialising in the long-term effects of emotionally immature parents.'),
  ('viktor-e-frankl',           'Viktor E. Frankl',                'Austrian psychiatrist, Holocaust survivor, and founder of logotherapy.'),
  ('bessel-van-der-kolk',       'Bessel van der Kolk',             'Psychiatrist and researcher who transformed understanding of trauma and the body.'),
  ('amir-levine',               'Amir Levine',                     'Psychiatrist and neuroscientist specialising in attachment theory and adult relationships.'),
  ('rachel-sf-heller',          'Rachel S.F. Heller',              'Co-author of Attached, focusing on attachment styles in adult relationships.'),
  ('richard-c-schwartz',        'Richard C. Schwartz',             'Founder of Internal Family Systems therapy.'),
  ('julie-smith',               'Dr Julie Smith',                  'Clinical psychologist and social media educator on everyday mental health.'),
  ('elaine-n-aron',             'Elaine N. Aron',                  'Research psychologist who introduced the concept of the Highly Sensitive Person.'),
  ('susanna-clarke',            'Susanna Clarke',                  'British author of Jonathan Strange & Mr Norrell and Piranesi.'),
  ('ashley-audrain',            'Ashley Audrain',                  'Canadian author of psychological thrillers exploring motherhood and doubt.'),
  ('yoko-ogawa',                'Yoko Ogawa',                      'Japanese literary author known for quietly surreal and deeply unsettling fiction.'),
  ('agustina-bazterrica',       'Agustina Bazterrica',             'Argentine dystopian author whose work dissects societal normalisation of horror.'),
  ('sayaka-murata',             'Sayaka Murata',                   'Japanese author of darkly comic fiction about alienation and social nonconformity.'),
  ('rf-kuang',                  'R.F. Kuang',                      'Author of fantasy and literary fiction exploring power, race, and ambition.'),
  ('daniel-kahneman',           'Daniel Kahneman',                 'Nobel-winning psychologist and pioneer of behavioural economics.'),
  ('robert-b-cialdini',         'Robert B. Cialdini',              'Social psychologist and world authority on influence and persuasion.'),
  ('carol-s-dweck',             'Carol S. Dweck',                  'Stanford professor and originator of the growth mindset framework.'),
  ('susan-cain',                'Susan Cain',                      'Author and former lawyer advocating for introverts in an extrovert-biased world.'),
  ('daniel-goleman',            'Daniel Goleman',                  'Psychologist who popularised the concept of emotional intelligence.'),
  ('dan-ariely',                'Dan Ariely',                      'Behavioural economist known for experiments on human irrationality.'),
  ('robert-m-sapolsky',         'Robert M. Sapolsky',              'Stanford neurobiologist and primatologist studying the biology of human behaviour.'),
  ('oliver-sacks',              'Oliver Sacks',                    'Neurologist and author celebrated for his compassionate case studies of the mind.'),
  ('robert-greene',             'Robert Greene',                   'Author of bestselling books on power, seduction, and human nature.'),
  ('charles-duhigg',            'Charles Duhigg',                  'Pulitzer Prize-winning journalist and author on habits, productivity, and communication.'),
  ('owen-okane',                'Owen O''Kane',                    'Psychotherapist and author on anxiety, OCD, and mental health literacy.'),
  ('mel-robbins',               'Mel Robbins',                     'Motivational speaker and author known for bold, practical frameworks for change.'),
  ('ichiro-kishimi',            'Ichiro Kishimi',                  'Japanese philosopher and Adlerian psychology expert.'),
  ('fumitake-koga',             'Fumitake Koga',                   'Japanese author and co-writer exploring Adlerian philosophy for modern readers.'),
  ('morgan-housel',             'Morgan Housel',                   'Partner at Collaborative Fund and author on the psychology of money and wealth.'),
  ('tj-power',                  'TJ Power',                        'Neuroscience communicator and author on dopamine, mood, and lifestyle design.'),
  ('bruce-d-perry',             'Bruce D. Perry',                  'Child psychiatrist and neuroscientist specialising in childhood trauma.'),
  ('oprah-winfrey',             'Oprah Winfrey',                   'Media executive, philanthropist, and co-author on trauma and healing.'),
  ('daniel-gilbert',            'Daniel Gilbert',                  'Harvard psychologist and author on affective forecasting and the pursuit of happiness.'),
  ('esther-perel',              'Esther Perel',                    'Belgian-American psychotherapist and author on desire, relationships, and human connection.')
ON CONFLICT (slug) DO NOTHING;

-- ── 5. BOOKS ────────────────────────────────────────────────
INSERT INTO public.books (slug, title, description, keywords, rating, formats, is_published)
VALUES
-- FICTION ──────────────────────────────────────────
('the-children',
 'The Children',
 'Childhood mythology, memory, family legacy, and author worship collide in this speculative Gothic novel. Strong 2026 fiction angle with adult fairy-tale energy.',
 ARRAY['gothic-fiction','speculative-fiction','childhood','mythology'],
 3.6, ARRAY['eBook','Paperback']::book_format[], true),

('we-love-you-bunny',
 'We Love You, Bunny',
 'Belonging can be beautiful. It can also bite. A razor-sharp dark comedy where obsession and literary horror meet.',
 ARRAY['dark-academia','literary-horror','obsession','satire'],
 3.4, ARRAY['eBook','Paperback']::book_format[], true),

('the-bewitching',
 'The Bewitching',
 'The past does not stay buried. It studies us. Gothic horror steeped in dread and atmosphere.',
 ARRAY['gothic-fiction','horror','atmosphere'],
 3.8, ARRAY['eBook','Paperback']::book_format[], true),

('what-moves-the-dead',
 'What Moves the Dead',
 'Decay. Dread. Devotion. A house remembers everything. A Gothic reimagining of Poe''s classic.',
 ARRAY['gothic-fiction','horror','poe','atmosphere'],
 3.8, ARRAY['eBook','Paperback']::book_format[], true),

('our-share-of-night',
 'Our Share of Night',
 'Power is inherited. So is the damage. A sweeping literary horror epic spanning decades of a family''s dark inheritance.',
 ARRAY['literary-horror','family','power','dark'],
 4.2, ARRAY['eBook','Paperback']::book_format[], true),

('nightbitch',
 'Nightbitch',
 'Motherhood. Rage. Metamorphosis. The body finally speaks. Feminist magical realism that refuses to stay polite.',
 ARRAY['magical-realism','feminism','motherhood','transformation'],
 3.4, ARRAY['eBook','Paperback']::book_format[], true),

('cursed-bunny',
 'Cursed Bunny',
 'The strange becomes familiar when society is sick. Speculative short fiction that holds a dark mirror to the everyday.',
 ARRAY['speculative-fiction','short-stories','social-critique'],
 3.7, ARRAY['eBook','Paperback']::book_format[], true),

('the-death-of-vivek-oji',
 'The Death of Vivek Oji',
 'A life can be loved and still misunderstood. A devastating and tender novel about identity, grief, and belonging in Nigeria.',
 ARRAY['african-literary-fiction','identity','grief','family'],
 4.1, ARRAY['eBook','Paperback']::book_format[], true),

('a-girl-is-a-body-of-water',
 'A Girl Is a Body of Water',
 'Girlhood is not soft. It is survival training. An intergenerational saga about women, power, and tradition in Uganda.',
 ARRAY['african-literary-fiction','girlhood','family','tradition'],
 4.1, ARRAY['eBook','Paperback']::book_format[], true),

('my-sister-the-serial-killer',
 'My Sister, the Serial Killer',
 'Love. Loyalty. Murder. Family makes terrible witnesses. A darkly comic thriller set in Lagos.',
 ARRAY['psychological-thriller','dark-comedy','family','nigeria'],
 3.6, ARRAY['eBook','Paperback']::book_format[], true),

('the-ancient-ones',
 'The Ancient Ones',
 'Ancient hunger wears a very human face. Small press dark fiction that taps deep into myth and dread.',
 ARRAY['gothic-fiction','dark-fiction','mythology','horror'],
 NULL, ARRAY['eBook']::book_format[], true),

('the-quiet-stillness-of-empty-houses',
 'The Quiet Stillness of Empty Houses',
 'Silence is never empty in a haunted house. Gothic fiction at its most atmospheric and intimate.',
 ARRAY['gothic-fiction','haunting','atmosphere','silence'],
 3.9, ARRAY['eBook','Paperback']::book_format[], true),

('piranesi',
 'Piranesi',
 'A beautiful prison is still a prison. A singular, mysterious novel about memory, identity, and a house that contains the world.',
 ARRAY['speculative-fiction','gothic-fiction','mystery','memory'],
 4.2, ARRAY['eBook','Paperback']::book_format[], true),

('the-push',
 'The Push',
 'Motherhood. Doubt. Fear. The mind turns against itself. A propulsive psychological thriller about the darkness inside love.',
 ARRAY['psychological-thriller','motherhood','doubt','suspense'],
 4.0, ARRAY['eBook','Paperback']::book_format[], true),

('the-memory-police',
 'The Memory Police',
 'When memory disappears, identity starts to vanish too. A haunting speculative novel about loss, forgetting, and erasure.',
 ARRAY['speculative-fiction','memory','loss','dystopia'],
 3.7, ARRAY['eBook','Paperback']::book_format[], true),

('tender-is-the-flesh',
 'Tender Is the Flesh',
 'A society can normalise anything if language helps. A disturbing dystopian novel about complicity and consumption.',
 ARRAY['literary-horror','dystopia','social-critique','dark'],
 3.8, ARRAY['eBook','Paperback']::book_format[], true),

('earthlings',
 'Earthlings',
 'Normal is the costume. Alienation is the truth underneath. A radically strange novel about belonging and survival.',
 ARRAY['magical-realism','alienation','dark-comedy','society'],
 3.6, ARRAY['eBook','Paperback']::book_format[], true),

('yellowface',
 'Yellowface',
 'Envy writes quickly when shame holds the pen. A sharp, provocative novel about race, theft, and the publishing industry.',
 ARRAY['psychological-thriller','dark-academia','race','publishing'],
 3.7, ARRAY['eBook','Paperback']::book_format[], true),

-- NONFICTION ───────────────────────────────────────
('the-anxious-generation',
 'The Anxious Generation',
 'Childhood changed. Anxiety followed. The phone was there. A landmark diagnosis of the teen mental health crisis.',
 ARRAY['psychology','anxiety','technology','society','parenting'],
 4.3, ARRAY['eBook','Paperback']::book_format[], true),

('dopamine-nation',
 'Dopamine Nation',
 'Pleasure. Pain. Craving. The brain keeps score. A Stanford psychiatrist''s revelatory look at addiction in the age of excess.',
 ARRAY['psychology','addiction','neuroscience','behaviour'],
 3.9, ARRAY['eBook','Paperback']::book_format[], true),

('stolen-focus',
 'Stolen Focus',
 'Your focus was not lost. It was taken. A journalist investigates why we cannot pay attention and who profits from it.',
 ARRAY['psychology','attention','technology','focus','society'],
 4.2, ARRAY['eBook','Paperback']::book_format[], true),

('the-myth-of-normal',
 'The Myth of Normal',
 'Normal can be comfortable. Normal can be costly. A radical rethink of health, trauma, and what society calls ordinary.',
 ARRAY['psychology','trauma','culture','health','society'],
 4.3, ARRAY['eBook','Paperback']::book_format[], true),

('maybe-you-should-talk-to-someone',
 'Maybe You Should Talk to Someone',
 'Therapy begins where the performance finally ends. A therapist goes to therapy — funny, devastating, and completely honest.',
 ARRAY['psychology','therapy','memoir','mental-health'],
 4.4, ARRAY['eBook','Paperback']::book_format[], true),

('mans-search-for-meaning',
 'Man''s Search for Meaning',
 'Meaning does not erase suffering. It gives it somewhere to stand. Viktor Frankl''s foundational account of survival and purpose.',
 ARRAY['philosophy','trauma','meaning','survival','existentialism'],
 4.4, ARRAY['eBook','Paperback']::book_format[], true),

('the-body-keeps-the-score',
 'The Body Keeps the Score',
 'The body remembers what the mind tried to survive. The definitive account of trauma''s lasting physical and psychological toll.',
 ARRAY['psychology','trauma','neuroscience','healing','body'],
 4.3, ARRAY['eBook','Paperback']::book_format[], true),

('the-righteous-mind',
 'The Righteous Mind',
 'We judge first. We explain ourselves later. A moral psychologist''s account of why good people are divided by politics and religion.',
 ARRAY['psychology','morality','politics','society'],
 4.2, ARRAY['eBook','Paperback']::book_format[], true),

('thinking-fast-and-slow',
 'Thinking, Fast and Slow',
 'The mind moves fast. Truth often walks behind it. Nobel laureate Daniel Kahneman''s masterwork on the two systems of thought.',
 ARRAY['psychology','decision-making','behavioural-economics','cognition'],
 4.2, ARRAY['eBook','Paperback']::book_format[], true),

('influence',
 'Influence',
 'Persuasion works best when it feels like your idea. The definitive science of how and why people say yes.',
 ARRAY['psychology','persuasion','behaviour','marketing'],
 4.2, ARRAY['eBook','Paperback']::book_format[], true),

('mindset',
 'Mindset',
 'A fixed mind protects itself. A growing mind practices. Carol Dweck''s transformative research on how beliefs shape achievement.',
 ARRAY['psychology','growth-mindset','education','achievement'],
 4.1, ARRAY['eBook','Paperback']::book_format[], true),

('quiet',
 'Quiet',
 'Quiet is not absence. It is a different kind of power. A passionate case for introverts in a world that will not stop talking.',
 ARRAY['psychology','introversion','personality','culture'],
 4.1, ARRAY['eBook','Paperback']::book_format[], true),

('emotional-intelligence',
 'Emotional Intelligence',
 'Feeling is data. Wisdom is learning how to read it. Daniel Goleman''s landmark exploration of EQ over IQ.',
 ARRAY['psychology','emotional-intelligence','behaviour','leadership'],
 4.0, ARRAY['eBook','Paperback']::book_format[], true),

('predictably-irrational',
 'Predictably Irrational',
 'We are irrational in patterns, not at random. Dan Ariely''s entertaining deep-dive into the hidden forces shaping decisions.',
 ARRAY['psychology','behavioural-economics','decision-making','irrationality'],
 4.1, ARRAY['eBook','Paperback']::book_format[], true),

('behave',
 'Behave',
 'Behaviour has roots deeper than the moment. Sapolsky''s monumental biology of what makes us human — and violent, and kind.',
 ARRAY['psychology','neuroscience','biology','human-behaviour'],
 4.4, ARRAY['eBook','Paperback']::book_format[], true),

('the-happiness-hypothesis',
 'The Happiness Hypothesis',
 'Happiness is older than self-help. Jonathan Haidt weaves ancient wisdom and modern psychology into a guide for living well.',
 ARRAY['psychology','philosophy','happiness','positive-psychology'],
 4.1, ARRAY['eBook','Paperback']::book_format[], true),

('the-man-who-mistook-his-wife-for-a-hat',
 'The Man Who Mistook His Wife for a Hat',
 'The brain can lose a map and still search for home. Oliver Sacks'' compassionate case studies of neurological wonder.',
 ARRAY['psychology','neuroscience','clinical','memoir'],
 4.1, ARRAY['eBook','Paperback']::book_format[], true),

('the-laws-of-human-nature',
 'The Laws of Human Nature',
 'People tell the truth before they speak it. Robert Greene''s sweeping study of the hidden forces driving human behaviour.',
 ARRAY['psychology','human-nature','behaviour','power'],
 4.4, ARRAY['eBook','Paperback']::book_format[], true),

('the-psychology-of-money',
 'The Psychology of Money',
 'Money behaviour is rarely just about money. Morgan Housel''s essential guide to the emotional and psychological side of wealth.',
 ARRAY['psychology','money','behaviour','finance'],
 NULL, ARRAY['eBook','Paperback']::book_format[], true),

('the-courage-to-be-disliked',
 'The Courage to Be Disliked',
 'Freedom begins when approval stops being the goal. Adlerian philosophy in an accessible Socratic dialogue format.',
 ARRAY['psychology','philosophy','freedom','adler'],
 NULL, ARRAY['eBook','Paperback']::book_format[], true),

('supercommunicators',
 'Supercommunicators',
 'Connection starts when we know which conversation we are in. Duhigg''s science of deep, effective communication.',
 ARRAY['psychology','communication','connection','relationships'],
 NULL, ARRAY['eBook','Paperback']::book_format[], true),

('stumbling-on-happiness',
 'Stumbling on Happiness',
 'We chase happiness with a faulty forecast. Harvard psychologist Daniel Gilbert on why our predictions about the future go wrong.',
 ARRAY['psychology','happiness','forecasting','cognitive-bias'],
 NULL, ARRAY['eBook','Paperback']::book_format[], true),

('mating-in-captivity',
 'Mating in Captivity',
 'Desire needs safety, but it also needs space. Esther Perel''s provocative exploration of eroticism and long-term love.',
 ARRAY['psychology','relationships','desire','intimacy'],
 NULL, ARRAY['eBook','Paperback']::book_format[], true),

-- SELF-HELP ───────────────────────────────────────
('set-boundaries-find-peace',
 'Set Boundaries, Find Peace',
 'Peace begins where people stop crossing you. A practical, empathetic guide to establishing healthy limits in every relationship.',
 ARRAY['self-help','psychology','boundaries','mental-health'],
 4.2, ARRAY['eBook','Paperback']::book_format[], true),

('meditations-for-mortals',
 'Meditations for Mortals',
 'You are finite. That is not failure. Oliver Burkeman''s invitation to embrace limits and find freedom in impermanence.',
 ARRAY['self-help','philosophy','productivity','time','mortality'],
 4.3, ARRAY['eBook','Paperback']::book_format[], true),

('the-mountain-is-you',
 'The Mountain Is You',
 'The mountain is not outside you. It answers from within. A guide to understanding and dismantling self-sabotage.',
 ARRAY['self-help','healing','self-sabotage','growth'],
 4.0, ARRAY['eBook','Paperback']::book_format[], true),

('atomic-habits',
 'Atomic Habits',
 'Small habits. Quiet proof. A new identity forming. The definitive modern guide to building good habits and breaking bad ones.',
 ARRAY['self-help','habits','behaviour','productivity','identity'],
 4.3, ARRAY['eBook','Paperback']::book_format[], true),

('adult-children-of-emotionally-immature-parents',
 'Adult Children of Emotionally Immature Parents',
 'Some childhoods end. Their emotional weather remains. A psychologist helps adults recognise and recover from emotionally immature parenting.',
 ARRAY['self-help','psychology','trauma','parenting','healing'],
 4.4, ARRAY['eBook','Paperback']::book_format[], true),

('attached',
 'Attached',
 'Closeness is not weakness. Distance is not always freedom. The science of adult attachment styles and how they shape every relationship.',
 ARRAY['self-help','psychology','relationships','attachment'],
 4.1, ARRAY['eBook','Paperback']::book_format[], true),

('no-bad-parts',
 'No Bad Parts',
 'No part of you is the enemy. Richard Schwartz introduces Internal Family Systems — a compassionate map of the inner world.',
 ARRAY['self-help','psychology','trauma','ifs','healing'],
 4.1, ARRAY['eBook','Paperback']::book_format[], true),

('why-has-nobody-told-me-this-before',
 'Why Has Nobody Told Me This Before?',
 'Mental health is built in ordinary moments. Dr Julie Smith translates clinical knowledge into practical everyday tools.',
 ARRAY['self-help','psychology','mental-health','tools'],
 3.9, ARRAY['eBook','Paperback']::book_format[], true),

('the-highly-sensitive-person',
 'The Highly Sensitive Person',
 'Sensitivity is not fragility. It is a different signal system. The foundational guide to understanding the HSP trait.',
 ARRAY['psychology','sensitivity','personality','traits'],
 3.8, ARRAY['eBook','Paperback']::book_format[], true),

('the-power-of-habit',
 'The Power of Habit',
 'Habits are decisions we stopped noticing. Charles Duhigg''s investigation into the science of habit formation and change.',
 ARRAY['self-help','habits','behaviour','neuroscience'],
 NULL, ARRAY['eBook','Paperback']::book_format[], true),

('addicted-to-anxiety',
 'Addicted to Anxiety',
 'Anxiety can become a habit. Awareness breaks the loop. A psychotherapist''s practical guide to ending the anxiety cycle.',
 ARRAY['self-help','psychology','anxiety','therapy'],
 NULL, ARRAY['eBook','Paperback']::book_format[], true),

('the-let-them-theory',
 'The Let Them Theory',
 'Letting go can be a discipline, not a surrender. Mel Robbins on releasing what you cannot control to reclaim your energy.',
 ARRAY['self-help','psychology','control','stress','mindset'],
 NULL, ARRAY['eBook','Paperback']::book_format[], true),

('what-happened-to-you',
 'What Happened to You?',
 'Healing often starts with a better question. Bruce Perry and Oprah Winfrey reframe trauma through conversations about compassion.',
 ARRAY['self-help','psychology','trauma','healing','compassion'],
 NULL, ARRAY['eBook','Paperback']::book_format[], true),

('the-dose-effect',
 'The DOSE Effect',
 'Mood is biology, behaviour, and repetition. TJ Power breaks down the four neurochemicals — dopamine, oxytocin, serotonin, endorphins.',
 ARRAY['self-help','psychology','neuroscience','mood','habits'],
 NULL, ARRAY['eBook','Paperback']::book_format[], true)

ON CONFLICT (slug) DO NOTHING;

-- ── 6. BOOKS ↔ AUTHORS ───────────────────────────────────────
INSERT INTO public.books_authors (book_id, author_id, position)
SELECT b.id, a.id, 1 FROM public.books b JOIN public.authors a ON true
WHERE (b.slug, a.slug) IN (
  ('the-children',                            'melissa-albert'),
  ('we-love-you-bunny',                       'mona-awad'),
  ('the-bewitching',                          'silvia-moreno-garcia'),
  ('what-moves-the-dead',                     't-kingfisher'),
  ('our-share-of-night',                      'mariana-enriquez'),
  ('nightbitch',                              'rachel-yoder'),
  ('cursed-bunny',                            'bora-chung'),
  ('the-death-of-vivek-oji',                  'akwaeke-emezi'),
  ('a-girl-is-a-body-of-water',               'jennifer-nansubuga-makumbi'),
  ('my-sister-the-serial-killer',             'oyinkan-braithwaite'),
  ('the-ancient-ones',                        'cassandra-l-thompson'),
  ('the-quiet-stillness-of-empty-houses',     'lv-russell'),
  ('the-anxious-generation',                  'jonathan-haidt'),
  ('dopamine-nation',                         'anna-lembke'),
  ('stolen-focus',                            'johann-hari'),
  ('the-myth-of-normal',                      'gabor-mate'),
  ('set-boundaries-find-peace',               'nedra-glover-tawwab'),
  ('meditations-for-mortals',                 'oliver-burkeman'),
  ('the-mountain-is-you',                     'brianna-wiest'),
  ('atomic-habits',                           'james-clear'),
  ('maybe-you-should-talk-to-someone',        'lori-gottlieb'),
  ('adult-children-of-emotionally-immature-parents', 'lindsay-c-gibson'),
  ('mans-search-for-meaning',                 'viktor-e-frankl'),
  ('the-body-keeps-the-score',                'bessel-van-der-kolk'),
  ('attached',                                'amir-levine'),
  ('no-bad-parts',                            'richard-c-schwartz'),
  ('why-has-nobody-told-me-this-before',      'julie-smith'),
  ('the-highly-sensitive-person',             'elaine-n-aron'),
  ('piranesi',                                'susanna-clarke'),
  ('the-push',                                'ashley-audrain'),
  ('the-memory-police',                       'yoko-ogawa'),
  ('tender-is-the-flesh',                     'agustina-bazterrica'),
  ('earthlings',                              'sayaka-murata'),
  ('yellowface',                              'rf-kuang'),
  ('the-righteous-mind',                      'jonathan-haidt'),
  ('thinking-fast-and-slow',                  'daniel-kahneman'),
  ('influence',                               'robert-b-cialdini'),
  ('mindset',                                 'carol-s-dweck'),
  ('quiet',                                   'susan-cain'),
  ('emotional-intelligence',                  'daniel-goleman'),
  ('predictably-irrational',                  'dan-ariely'),
  ('behave',                                  'robert-m-sapolsky'),
  ('the-happiness-hypothesis',                'jonathan-haidt'),
  ('the-man-who-mistook-his-wife-for-a-hat',  'oliver-sacks'),
  ('the-laws-of-human-nature',                'robert-greene'),
  ('the-power-of-habit',                      'charles-duhigg'),
  ('addicted-to-anxiety',                     'owen-okane'),
  ('the-let-them-theory',                     'mel-robbins'),
  ('the-courage-to-be-disliked',              'ichiro-kishimi'),
  ('the-psychology-of-money',                 'morgan-housel'),
  ('the-dose-effect',                         'tj-power'),
  ('what-happened-to-you',                    'bruce-d-perry'),
  ('supercommunicators',                      'charles-duhigg'),
  ('stumbling-on-happiness',                  'daniel-gilbert'),
  ('mating-in-captivity',                     'esther-perel')
)
ON CONFLICT DO NOTHING;

-- Co-authors (position 2)
INSERT INTO public.books_authors (book_id, author_id, position)
SELECT b.id, a.id, 2 FROM public.books b JOIN public.authors a ON true
WHERE (b.slug, a.slug) IN (
  ('attached',                    'rachel-sf-heller'),
  ('the-courage-to-be-disliked',  'fumitake-koga'),
  ('what-happened-to-you',        'oprah-winfrey')
)
ON CONFLICT DO NOTHING;

-- ── 7. BOOKS ↔ GENRES ────────────────────────────────────────
INSERT INTO public.books_genres (book_id, genre_id)
SELECT b.id, g.id FROM public.books b JOIN public.genres g ON true
WHERE (b.slug, g.slug) IN (
  -- Fiction books
  ('the-children',                        'fiction'),
  ('the-children',                        'gothic-fiction'),
  ('the-children',                        'speculative-fiction'),
  ('we-love-you-bunny',                   'fiction'),
  ('we-love-you-bunny',                   'dark-academia'),
  ('we-love-you-bunny',                   'literary-horror'),
  ('the-bewitching',                      'fiction'),
  ('the-bewitching',                      'gothic-fiction'),
  ('the-bewitching',                      'literary-horror'),
  ('what-moves-the-dead',                 'fiction'),
  ('what-moves-the-dead',                 'gothic-fiction'),
  ('our-share-of-night',                  'fiction'),
  ('our-share-of-night',                  'literary-horror'),
  ('nightbitch',                          'fiction'),
  ('nightbitch',                          'magical-realism'),
  ('cursed-bunny',                        'fiction'),
  ('cursed-bunny',                        'speculative-fiction'),
  ('the-death-of-vivek-oji',              'fiction'),
  ('the-death-of-vivek-oji',             'african-literary-fiction'),
  ('a-girl-is-a-body-of-water',           'fiction'),
  ('a-girl-is-a-body-of-water',          'african-literary-fiction'),
  ('my-sister-the-serial-killer',         'fiction'),
  ('my-sister-the-serial-killer',        'psychological-thriller'),
  ('the-ancient-ones',                    'fiction'),
  ('the-ancient-ones',                    'gothic-fiction'),
  ('the-quiet-stillness-of-empty-houses', 'fiction'),
  ('the-quiet-stillness-of-empty-houses','gothic-fiction'),
  ('piranesi',                            'fiction'),
  ('piranesi',                            'speculative-fiction'),
  ('piranesi',                            'gothic-fiction'),
  ('the-push',                            'fiction'),
  ('the-push',                            'psychological-thriller'),
  ('the-memory-police',                   'fiction'),
  ('the-memory-police',                   'speculative-fiction'),
  ('tender-is-the-flesh',                 'fiction'),
  ('tender-is-the-flesh',                 'literary-horror'),
  ('earthlings',                          'fiction'),
  ('earthlings',                          'magical-realism'),
  ('yellowface',                          'fiction'),
  ('yellowface',                          'psychological-thriller'),
  ('yellowface',                          'dark-academia'),
  -- Nonfiction books
  ('the-anxious-generation',              'nonfiction'),
  ('the-anxious-generation',              'psychology'),
  ('dopamine-nation',                     'nonfiction'),
  ('dopamine-nation',                     'psychology'),
  ('stolen-focus',                        'nonfiction'),
  ('stolen-focus',                        'psychology'),
  ('the-myth-of-normal',                  'nonfiction'),
  ('the-myth-of-normal',                  'psychology'),
  ('the-myth-of-normal',                  'trauma'),
  ('maybe-you-should-talk-to-someone',    'nonfiction'),
  ('maybe-you-should-talk-to-someone',    'psychology'),
  ('mans-search-for-meaning',             'nonfiction'),
  ('mans-search-for-meaning',             'philosophy'),
  ('mans-search-for-meaning',             'trauma'),
  ('the-body-keeps-the-score',            'nonfiction'),
  ('the-body-keeps-the-score',            'psychology'),
  ('the-body-keeps-the-score',            'trauma'),
  ('the-righteous-mind',                  'nonfiction'),
  ('the-righteous-mind',                  'psychology'),
  ('thinking-fast-and-slow',              'nonfiction'),
  ('thinking-fast-and-slow',              'psychology'),
  ('influence',                           'nonfiction'),
  ('influence',                           'psychology'),
  ('mindset',                             'nonfiction'),
  ('mindset',                             'psychology'),
  ('quiet',                               'nonfiction'),
  ('quiet',                               'psychology'),
  ('emotional-intelligence',              'nonfiction'),
  ('emotional-intelligence',              'psychology'),
  ('predictably-irrational',              'nonfiction'),
  ('predictably-irrational',              'psychology'),
  ('behave',                              'nonfiction'),
  ('behave',                              'psychology'),
  ('the-happiness-hypothesis',            'nonfiction'),
  ('the-happiness-hypothesis',            'psychology'),
  ('the-happiness-hypothesis',            'philosophy'),
  ('the-man-who-mistook-his-wife-for-a-hat','nonfiction'),
  ('the-man-who-mistook-his-wife-for-a-hat','psychology'),
  ('the-laws-of-human-nature',            'nonfiction'),
  ('the-laws-of-human-nature',            'psychology'),
  ('the-psychology-of-money',             'nonfiction'),
  ('the-psychology-of-money',             'psychology'),
  ('the-courage-to-be-disliked',          'nonfiction'),
  ('the-courage-to-be-disliked',          'psychology'),
  ('the-courage-to-be-disliked',          'philosophy'),
  ('supercommunicators',                  'nonfiction'),
  ('supercommunicators',                  'psychology'),
  ('supercommunicators',                  'relationships'),
  ('stumbling-on-happiness',              'nonfiction'),
  ('stumbling-on-happiness',              'psychology'),
  ('mating-in-captivity',                 'nonfiction'),
  ('mating-in-captivity',                 'psychology'),
  ('mating-in-captivity',                 'relationships'),
  ('the-highly-sensitive-person',         'nonfiction'),
  ('the-highly-sensitive-person',         'psychology'),
  -- Self-help books
  ('set-boundaries-find-peace',           'self-help'),
  ('set-boundaries-find-peace',           'psychology'),
  ('meditations-for-mortals',             'self-help'),
  ('meditations-for-mortals',             'philosophy'),
  ('the-mountain-is-you',                 'self-help'),
  ('the-mountain-is-you',                 'trauma'),
  ('atomic-habits',                       'self-help'),
  ('atomic-habits',                       'habits'),
  ('adult-children-of-emotionally-immature-parents','self-help'),
  ('adult-children-of-emotionally-immature-parents','psychology'),
  ('adult-children-of-emotionally-immature-parents','trauma'),
  ('attached',                            'self-help'),
  ('attached',                            'psychology'),
  ('attached',                            'relationships'),
  ('no-bad-parts',                        'self-help'),
  ('no-bad-parts',                        'psychology'),
  ('no-bad-parts',                        'trauma'),
  ('why-has-nobody-told-me-this-before',  'self-help'),
  ('why-has-nobody-told-me-this-before',  'psychology'),
  ('the-power-of-habit',                  'self-help'),
  ('the-power-of-habit',                  'habits'),
  ('addicted-to-anxiety',                 'self-help'),
  ('addicted-to-anxiety',                 'psychology'),
  ('the-let-them-theory',                 'self-help'),
  ('the-let-them-theory',                 'psychology'),
  ('what-happened-to-you',                'self-help'),
  ('what-happened-to-you',                'psychology'),
  ('what-happened-to-you',                'trauma'),
  ('the-dose-effect',                     'self-help'),
  ('the-dose-effect',                     'psychology'),
  ('the-dose-effect',                     'habits')
)
ON CONFLICT DO NOTHING;
