-- Auto-generated by scripts/enrich-books.mjs
-- Adds cover_url (Open Library) and buy links (Open Library + Bookshop.org).

UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/13524173-M.jpg' WHERE slug = 'the-children';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/15200275-M.jpg' WHERE slug = 'we-love-you-bunny';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/15101938-M.jpg' WHERE slug = 'the-bewitching';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/11710359-M.jpg' WHERE slug = 'what-moves-the-dead';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/10648437-M.jpg' WHERE slug = 'nightbitch';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/9285552-M.jpg' WHERE slug = 'the-death-of-vivek-oji';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/10331706-M.jpg' WHERE slug = 'a-girl-is-a-body-of-water';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/10721487-M.jpg' WHERE slug = 'my-sister-the-serial-killer';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/10226290-M.jpg' WHERE slug = 'piranesi';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/10540935-M.jpg' WHERE slug = 'the-push';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/15223719-M.jpg' WHERE slug = 'the-memory-police';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/13195421-M.jpg' WHERE slug = 'yellowface';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/15104803-M.jpg' WHERE slug = 'the-anxious-generation';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/11757830-M.jpg' WHERE slug = 'dopamine-nation';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/12664855-M.jpg' WHERE slug = 'stolen-focus';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/8596019-M.jpg' WHERE slug = 'maybe-you-should-talk-to-someone';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/11203708-M.jpg' WHERE slug = 'mans-search-for-meaning';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/8315367-M.jpg' WHERE slug = 'the-body-keeps-the-score';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/7256782-M.jpg' WHERE slug = 'the-righteous-mind';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/13290711-M.jpg' WHERE slug = 'thinking-fast-and-slow';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/431011-M.jpg' WHERE slug = 'influence';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/746414-M.jpg' WHERE slug = 'mindset';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/7079753-M.jpg' WHERE slug = 'quiet';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/1359485-M.jpg' WHERE slug = 'emotional-intelligence';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/2314080-M.jpg' WHERE slug = 'predictably-irrational';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/8814831-M.jpg' WHERE slug = 'behave';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/298622-M.jpg' WHERE slug = 'the-happiness-hypothesis';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/6986188-M.jpg' WHERE slug = 'the-man-who-mistook-his-wife-for-a-hat';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/10170095-M.jpg' WHERE slug = 'the-laws-of-human-nature';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/10389354-M.jpg' WHERE slug = 'the-psychology-of-money';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/14591638-M.jpg' WHERE slug = 'supercommunicators';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/6803663-M.jpg' WHERE slug = 'stumbling-on-happiness';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/46486-M.jpg' WHERE slug = 'mating-in-captivity';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/10543310-M.jpg' WHERE slug = 'set-boundaries-find-peace';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/15091836-M.jpg' WHERE slug = 'meditations-for-mortals';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/13838236-M.jpg' WHERE slug = 'the-mountain-is-you';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/12539702-M.jpg' WHERE slug = 'atomic-habits';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/11301956-M.jpg' WHERE slug = 'adult-children-of-emotionally-immature-parents';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/8620497-M.jpg' WHERE slug = 'attached';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/10881934-M.jpg' WHERE slug = 'no-bad-parts';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/12821544-M.jpg' WHERE slug = 'why-has-nobody-told-me-this-before';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/367868-M.jpg' WHERE slug = 'the-highly-sensitive-person';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/9078085-M.jpg' WHERE slug = 'the-power-of-habit';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/15165806-M.jpg' WHERE slug = 'the-let-them-theory';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/10880114-M.jpg' WHERE slug = 'what-happened-to-you';
UPDATE public.books SET cover_url = 'https://covers.openlibrary.org/b/id/15098957-M.jpg' WHERE slug = 'the-dose-effect';

-- Ensure open-library retailer exists
INSERT INTO public.retailers (slug, label) VALUES ('open-library', 'Open Library') ON CONFLICT (slug) DO NOTHING;

-- Buy links (Open Library + Bookshop.org)
DO $$
DECLARE
  ol_id uuid; bs_id uuid; book_id uuid;
BEGIN
  SELECT id INTO ol_id FROM public.retailers WHERE slug = 'open-library';
  SELECT id INTO bs_id FROM public.retailers WHERE slug = 'bookshop';

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-children';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL184533W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20Children%20Melissa%20Albert')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'we-love-you-bunny';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL42544076W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=We%20Love%20You%2C%20Bunny%20Mona%20Awad')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-bewitching';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL43671510W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20Bewitching%20Silvia%20Moreno-Garcia')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'what-moves-the-dead';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL24850157W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=What%20Moves%20the%20Dead%20T.%20Kingfisher')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'our-share-of-night';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/search?title=Our%20Share%20of%20Night&author=Mariana%20Enriquez')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Our%20Share%20of%20Night%20Mariana%20Enriquez')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'nightbitch';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL24205143W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Nightbitch%20Rachel%20Yoder')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'cursed-bunny';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/search?title=Cursed%20Bunny&author=Bora%20Chung')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Cursed%20Bunny%20Bora%20Chung')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-death-of-vivek-oji';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL20649783W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20Death%20of%20Vivek%20Oji%20Akwaeke%20Emezi')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'a-girl-is-a-body-of-water';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL21176144W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=A%20Girl%20Is%20a%20Body%20of%20Water%20Jennifer%20Nansubuga%20Makumbi')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'my-sister-the-serial-killer';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL19761909W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=My%20Sister%2C%20the%20Serial%20Killer%20Oyinkan%20Braithwaite')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-ancient-ones';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL25299505W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20Ancient%20Ones%20Cassandra%20L.%20Thompson')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-quiet-stillness-of-empty-houses';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/search?title=The%20Quiet%20Stillness%20of%20Empty%20Houses&author=L.V.%20Russell')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20Quiet%20Stillness%20of%20Empty%20Houses%20L.V.%20Russell')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'piranesi';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL20893680W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Piranesi%20Susanna%20Clarke')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-push';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL21694014W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20Push%20Ashley%20Audrain')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-memory-police';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL45560574W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20Memory%20Police%20Yoko%20Ogawa')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'tender-is-the-flesh';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/search?title=Tender%20Is%20the%20Flesh&author=Agustina%20Bazterrica')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Tender%20Is%20the%20Flesh%20Agustina%20Bazterrica')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'earthlings';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/search?title=Earthlings&author=Sayaka%20Murata')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Earthlings%20Sayaka%20Murata')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'yellowface';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL29050559W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Yellowface%20R.F.%20Kuang')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-anxious-generation';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL37575384W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20Anxious%20Generation%20Jonathan%20Haidt')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'dopamine-nation';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL24868953W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Dopamine%20Nation%20Anna%20Lembke')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'stolen-focus';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL25453949W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Stolen%20Focus%20Johann%20Hari')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-myth-of-normal';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/search?title=The%20Myth%20of%20Normal&author=Gabor%20Mat%C3%A9')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20Myth%20of%20Normal%20Gabor%20Mat%C3%A9')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'maybe-you-should-talk-to-someone';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL19791590W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Maybe%20You%20Should%20Talk%20to%20Someone%20Lori%20Gottlieb')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'mans-search-for-meaning';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL24557376W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Man''s%20Search%20for%20Meaning%20Viktor%20E.%20Frankl')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-body-keeps-the-score';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL18147687W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20Body%20Keeps%20the%20Score%20Bessel%20van%20der%20Kolk')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-righteous-mind';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL16568840W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20Righteous%20Mind%20Jonathan%20Haidt')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'thinking-fast-and-slow';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL15992072W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Thinking%2C%20Fast%20and%20Slow%20Daniel%20Kahneman')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'influence';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL3902892W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Influence%20Robert%20B.%20Cialdini')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'mindset';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL2003465W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Mindset%20Carol%20S.%20Dweck')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'quiet';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL16484595W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Quiet%20Susan%20Cain')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'emotional-intelligence';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL1878267W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Emotional%20Intelligence%20Daniel%20Goleman')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'predictably-irrational';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL9302660W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Predictably%20Irrational%20Dan%20Ariely')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'behave';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL17835813W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Behave%20Robert%20M.%20Sapolsky')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-happiness-hypothesis';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL5829273W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20Happiness%20Hypothesis%20Jonathan%20Haidt')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-man-who-mistook-his-wife-for-a-hat';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL1811898W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20Man%20Who%20Mistook%20His%20Wife%20for%20a%20Hat%20Oliver%20Sacks')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-laws-of-human-nature';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL19761410W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20Laws%20of%20Human%20Nature%20Robert%20Greene')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-psychology-of-money';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL21640039W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20Psychology%20of%20Money%20Morgan%20Housel')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-courage-to-be-disliked';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/search?title=The%20Courage%20to%20Be%20Disliked&author=Ichiro%20Kishimi')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20Courage%20to%20Be%20Disliked%20Ichiro%20Kishimi')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'supercommunicators';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL37564042W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Supercommunicators%20Charles%20Duhigg')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'stumbling-on-happiness';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL15840192W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Stumbling%20on%20Happiness%20Daniel%20Gilbert')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'mating-in-captivity';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL275862W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Mating%20in%20Captivity%20Esther%20Perel')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'set-boundaries-find-peace';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL24144951W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Set%20Boundaries%2C%20Find%20Peace%20Nedra%20Glover%20Tawwab')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'meditations-for-mortals';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL37584288W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Meditations%20for%20Mortals%20Oliver%20Burkeman')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-mountain-is-you';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL25436364W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20Mountain%20Is%20You%20Brianna%20Wiest')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'atomic-habits';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL17930368W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Atomic%20Habits%20James%20Clear')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'adult-children-of-emotionally-immature-parents';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL20006178W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Adult%20Children%20of%20Emotionally%20Immature%20Parents%20Lindsay%20C.%20Gibson')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'attached';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL16929630W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Attached%20Amir%20Levine')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'no-bad-parts';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL24355843W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=No%20Bad%20Parts%20Richard%20C.%20Schwartz')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'why-has-nobody-told-me-this-before';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL25799307W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Why%20Has%20Nobody%20Told%20Me%20This%20Before%3F%20Dr%20Julie%20Smith')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-highly-sensitive-person';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL856010W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20Highly%20Sensitive%20Person%20Elaine%20N.%20Aron')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-power-of-habit';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL16015154W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20Power%20of%20Habit%20Charles%20Duhigg')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'addicted-to-anxiety';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL42408458W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=Addicted%20to%20Anxiety%20Owen%20O''Kane')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-let-them-theory';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL39181496W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20Let%20Them%20Theory%20Mel%20Robbins')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'what-happened-to-you';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL24354365W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=What%20Happened%20to%20You%3F%20Bruce%20D.%20Perry')
    ON CONFLICT DO NOTHING;

  SELECT id INTO book_id FROM public.books WHERE slug = 'the-dose-effect';
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, ol_id, 'https://openlibrary.org/works/OL43504414W')
    ON CONFLICT DO NOTHING;
  INSERT INTO public.book_retailer_links (book_id, retailer_id, url)
    VALUES (book_id, bs_id, 'https://bookshop.org/search?keywords=The%20DOSE%20Effect%20TJ%20Power')
    ON CONFLICT DO NOTHING;

END $$;