-- Auto-generated by scripts/enrich-missing-covers.mjs
-- Adds cover_url for books that Open Library did not cover.

UPDATE public.books SET cover_url = 'https://books.google.com/books/content?id=YJxuEAAAQBAJ&printsec=frontcover&img=1&zoom=2&source=gbs_api' WHERE slug = 'our-share-of-night';
UPDATE public.books SET cover_url = 'https://books.google.com/books/content?id=v_2GEAAAQBAJ&printsec=frontcover&img=1&zoom=2&source=gbs_api' WHERE slug = 'cursed-bunny';
UPDATE public.books SET cover_url = 'https://books.google.com/books/content?id=SImEzwEACAAJ&printsec=frontcover&img=1&zoom=2&source=gbs_api' WHERE slug = 'the-quiet-stillness-of-empty-houses';
UPDATE public.books SET cover_url = 'https://books.google.com/books/content?id=Ut37DwAAQBAJ&printsec=frontcover&img=1&zoom=2&source=gbs_api' WHERE slug = 'the-ancient-ones';
UPDATE public.books SET cover_url = 'https://books.google.com/books/content?id=XaPGDwAAQBAJ&printsec=frontcover&img=1&zoom=2&source=gbs_api' WHERE slug = 'tender-is-the-flesh';
UPDATE public.books SET cover_url = 'https://books.google.com/books/content?id=JEAeygEACAAJ&printsec=frontcover&img=1&zoom=2&source=gbs_api' WHERE slug = 'earthlings';
UPDATE public.books SET cover_url = 'https://books.google.com/books/content?id=gPNZEQAAQBAJ&printsec=frontcover&img=1&zoom=2&source=gbs_api' WHERE slug = 'the-myth-of-normal';
UPDATE public.books SET cover_url = 'https://books.google.com/books/content?id=hGFEDwAAQBAJ&printsec=frontcover&img=1&zoom=2&source=gbs_api' WHERE slug = 'the-courage-to-be-disliked';
UPDATE public.books SET cover_url = 'https://books.google.com/books/content?id=NCjx0AEACAAJ&printsec=frontcover&img=1&zoom=2&source=gbs_api' WHERE slug = 'addicted-to-anxiety';