-- Seed: first two published blog posts from editorial sheet
INSERT INTO blogs (
  content_id, type, status, published_at,
  title, slug, pillar, audience,
  primary_keyword, secondary_keywords,
  excerpt, meta_title, meta_description,
  intro_hook, key_sections, cta, related_tool,
  social_asset_idea, source_reference,
  hero_image_brief, internal_links,
  notes, revision_notes
) VALUES
(
  'BN-001', 'blog', 'published', '2026-07-02 09:00:00+00',
  'How to Convert a Manuscript into a Clean EPUB Without Breaking the Reading Experience',
  'convert-manuscript-clean-epub',
  'EPUB Conversion',
  'Indie authors preparing to publish digitally',
  'clean EPUB conversion',
  ARRAY['manuscript to EPUB','ebook formatting','EPUB validation','indie author tools'],
  'A clean EPUB is not just a file export. It is a structured reading package with correct chapters, metadata, navigation, images and validation.',
  'Manuscript to Clean EPUB: Indie Author Guide',
  'Learn how to turn your manuscript into a clean EPUB with proper structure, metadata, navigation, images and validation before publishing.',
  'A book can look finished in Word and still fall apart inside an e-reader.',
  'What EPUB really is | Common conversion mistakes | Why structure matters | Checklist before publishing | How Indie Converters helps',
  'Explore Indie Converters author tools',
  'EPUB converter / Author tools',
  'Carousel: 5 signs your EPUB was badly converted',
  'W3C EPUB 3.3 Recommendation: https://www.w3.org/TR/epub-33/',
  'Clean desktop mockup showing manuscript converting into a polished EPUB on tablet or e-reader.',
  ARRAY['EPUB converter','Explore author tools','Book metadata checklist','EPUB accessibility guide','Indie Converters catalogue'],
  'Full draft written in linked Google Doc. Sheet row contains SEO fields and production notes.',
  'First full draft completed in linked Google Doc.'
),
(
  'BN-002', 'blog', 'published', '2026-07-05 09:00:00+00',
  'EPUB Accessibility: What Indie Authors Need to Know Before Publishing in 2026',
  'epub-accessibility-indie-authors-2026',
  'Accessibility',
  'Indie authors selling in Europe or through global retailers',
  'EPUB accessibility',
  ARRAY['accessible ebooks','alt text','accessibility metadata','European Accessibility Act'],
  'Your ebook should reach every reader — not just the ones without barriers. Accessibility is now a publishing standard, not an optional extra.',
  'EPUB Accessibility for Indie Authors 2026',
  'A practical guide to accessible EPUBs: metadata, alt text, navigation, reading order, and why the European Accessibility Act changes everything for indie publishers.',
  'Your ebook should not exclude readers before they reach page one.',
  'Why accessibility matters | Required accessibility metadata | Alt text and navigation | EU market context | Author checklist',
  'Convert your book into a cleaner, more accessible EPUB',
  'EPUB conversion + accessibility checklist',
  'News-style card: EPUB accessibility is now part of publishing quality',
  'W3C EPUB Accessibility 1.1; EU Directive 2019/882',
  'Split screen: inaccessible vs accessible EPUB side-by-side on a screen reader device.',
  ARRAY['EPUB converter','Accessibility checklist','Author tools','Indie Converters catalogue'],
  'Full accessibility blog written in linked Google Doc. Focus: EPUB structure, WCAG, metadata, EAA context, author checklist.',
  NULL
);
