-- Auto-generated by scripts/enrich-google-books-prices.mjs
-- Upserts source = 'google_books' retailer links; never touches author-declared rows.

insert into public.retailers (slug, label) values ('google-books', 'Google Books') on conflict (slug) do nothing;

insert into public.book_retailer_links (book_id, retailer_id, url, price, currency, source, price_updated_at)
select b.id, r.id, 'https://play.google.com/store/books/details?id=ga6NDwAAQBAJ&rdid=book-ga6NDwAAQBAJ&rdot=1&source=gbs_api', 11.55, 'EUR', 'google_books', now()
from public.books b, public.retailers r
where b.slug = 'the-factory' and r.slug = 'google-books'
on conflict (book_id, retailer_id) do update set
  url = excluded.url, price = excluded.price, currency = excluded.currency,
  source = 'google_books', price_updated_at = now();

insert into public.book_retailer_links (book_id, retailer_id, url, price, currency, source, price_updated_at)
select b.id, r.id, 'https://play.google.com/store/books/details?id=-bpVCgAAQBAJ&rdid=book--bpVCgAAQBAJ&rdot=1&source=gbs_api', 13.02, 'EUR', 'google_books', now()
from public.books b, public.retailers r
where b.slug = 'the-queue' and r.slug = 'google-books'
on conflict (book_id, retailer_id) do update set
  url = excluded.url, price = excluded.price, currency = excluded.currency,
  source = 'google_books', price_updated_at = now();

insert into public.book_retailer_links (book_id, retailer_id, url, price, currency, source, price_updated_at)
select b.id, r.id, 'https://play.google.com/store/books/details?id=QwSUDwAAQBAJ&rdid=book-QwSUDwAAQBAJ&rdot=1&source=gbs_api', 9.3, 'EUR', 'google_books', now()
from public.books b, public.retailers r
where b.slug = 'the-seep' and r.slug = 'google-books'
on conflict (book_id, retailer_id) do update set
  url = excluded.url, price = excluded.price, currency = excluded.currency,
  source = 'google_books', price_updated_at = now();

insert into public.book_retailer_links (book_id, retailer_id, url, price, currency, source, price_updated_at)
select b.id, r.id, 'https://play.google.com/store/books/details?id=EyHIAgAAQBAJ&rdid=book-EyHIAgAAQBAJ&rdot=1&source=gbs_api', 11.11, 'EUR', 'google_books', now()
from public.books b, public.retailers r
where b.slug = 'the-highly-sensitive-person' and r.slug = 'google-books'
on conflict (book_id, retailer_id) do update set
  url = excluded.url, price = excluded.price, currency = excluded.currency,
  source = 'google_books', price_updated_at = now();

insert into public.book_retailer_links (book_id, retailer_id, url, price, currency, source, price_updated_at)
select b.id, r.id, 'https://play.google.com/store/books/details?id=siiCEAAAQBAJ&rdid=book-siiCEAAAQBAJ&rdot=1&source=gbs_api', 23.42, 'EUR', 'google_books', now()
from public.books b, public.retailers r
where b.slug = 'yellowface' and r.slug = 'google-books'
on conflict (book_id, retailer_id) do update set
  url = excluded.url, price = excluded.price, currency = excluded.currency,
  source = 'google_books', price_updated_at = now();

insert into public.book_retailer_links (book_id, retailer_id, url, price, currency, source, price_updated_at)
select b.id, r.id, 'https://play.google.com/store/books/details?id=etzKCQAAQBAJ&rdid=book-etzKCQAAQBAJ&rdot=1&source=gbs_api', 9.49, 'EUR', 'google_books', now()
from public.books b, public.retailers r
where b.slug = 'the-happiness-hypothesis' and r.slug = 'google-books'
on conflict (book_id, retailer_id) do update set
  url = excluded.url, price = excluded.price, currency = excluded.currency,
  source = 'google_books', price_updated_at = now();

insert into public.book_retailer_links (book_id, retailer_id, url, price, currency, source, price_updated_at)
select b.id, r.id, 'https://play.google.com/store/books/details?id=6h8jkUBC4asC&rdid=book-6h8jkUBC4asC&rdot=1&source=gbs_api', 9.9, 'EUR', 'google_books', now()
from public.books b, public.retailers r
where b.slug = 'stumbling-on-happiness' and r.slug = 'google-books'
on conflict (book_id, retailer_id) do update set
  url = excluded.url, price = excluded.price, currency = excluded.currency,
  source = 'google_books', price_updated_at = now();

insert into public.book_retailer_links (book_id, retailer_id, url, price, currency, source, price_updated_at)
select b.id, r.id, 'https://play.google.com/store/books/details?id=THa4DgAAQBAJ&rdid=book-THa4DgAAQBAJ&rdot=1&source=gbs_api', 13.77, 'EUR', 'google_books', now()
from public.books b, public.retailers r
where b.slug = 'transparent-city' and r.slug = 'google-books'
on conflict (book_id, retailer_id) do update set
  url = excluded.url, price = excluded.price, currency = excluded.currency,
  source = 'google_books', price_updated_at = now();
